"""add cascade

Revision ID: 0384419a65ea
Revises: d62a332ec311
Create Date: 2026-02-17 17:53:08.882257

"""
from typing import Sequence, Union
    
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0384419a65ea'
down_revision: Union[str, Sequence[str], None] = 'd62a332ec311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
