"""add_goship_fields_to_order_and_address

Revision ID: 1be766acafcc
Revises: 9785780f5e00
Create Date: 2026-02-25 08:46:42.490617

"""
from typing import Sequence, Union
    
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1be766acafcc'
down_revision: Union[str, Sequence[str], None] = '9785780f5e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('address', sa.Column('district_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('address', sa.Column('ward_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('shipping_fee', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('rate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'rate_id')
    op.drop_column('order', 'shipping_fee')
    op.drop_column('order', 'tracking_number')
    op.drop_column('order', 'carrier')
    op.drop_column('order', 'shipping_code')
    op.drop_column('address', 'ward_name')
    op.drop_column('address', 'district_name')
    op.drop_column('address', 'city_name')
    op.drop_column('address', 'ward_id')
    op.drop_column('address', 'district_id')
    op.drop_column('address', 'city_id')
    # ### end Alembic commands ###
