"""add nullable for foreign key

Revision ID: d62a332ec311
Revises: 4442a8005130
Create Date: 2026-02-13 23:38:06.547496

"""
from typing import Sequence, Union
    
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd62a332ec311'
down_revision: Union[str, Sequence[str], None] = '4442a8005130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_detail_ibfk_1'), 'product_detail', type_='foreignkey')
    op.create_foreign_key(None, 'product_detail', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_image', 'id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_constraint(op.f('product_image_ibfk_1'), 'product_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.create_foreign_key(op.f('product_image_ibfk_1'), 'product_image', 'product', ['product_id'], ['id'])
    op.alter_column('product_image', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'product_detail', type_='foreignkey')
    op.create_foreign_key(op.f('product_detail_ibfk_1'), 'product_detail', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
