"""change some field in product model and product image model

Revision ID: 4442a8005130
Revises: 71ea746969a9
Create Date: 2026-01-29 14:35:53.155623

"""
from typing import Sequence, Union
    
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4442a8005130'
down_revision: Union[str, Sequence[str], None] = '71ea746969a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cover')
    op.drop_column('product_image', 'medium_url')
    op.drop_column('product_image', 'display_order')
    op.drop_column('product_image', 'is_primary')
    op.drop_column('product_image', 'alt_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('alt_text', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('product_image', sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('product_image', sa.Column('display_order', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('product_image', sa.Column('medium_url', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('product', sa.Column('cover', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
