"""add product image table

Revision ID: 71ea746969a9
Revises: c3ae775e76ff
Create Date: 2026-01-28 02:18:03.032755

"""
from typing import Sequence, Union
    
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '71ea746969a9'
down_revision: Union[str, Sequence[str], None] = 'c3ae775e76ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('cloudinary_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('medium_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    # ### end Alembic commands ###
